version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: studyapp_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: studyuser
      POSTGRES_PASSWORD: studypass
      POSTGRES_DB: studydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
