 
services:
  db:
    image: postgres:15
    container_name: study-app-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: studyapp
      POSTGRES_PASSWORD: studyapp123
      POSTGRES_DB: studyapp
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: study-app-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: db
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: studyapp
      TYPEORM_PASSWORD: studyapp123
      TYPEORM_DATABASE: studyapp
      TYPEORM_SYNCHRONIZE: "false"
      TYPEORM_LOGGING: "true"
      TYPEORM_ENTITIES: "dist/entities/*.entity.js"
      TYPEORM_MIGRATIONS: "dist/migrations/*.js"
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
    driver: local