-- Migration part 2
INSERT INTO study_app.preguntas (text_content, respuesta_correcta, raw_source) 
VALUES 
('31 Lea la siguiente situación:\nUn profesor está iniciando un proceso de lectura en un 1° Básico, para lo cual diseña su planificación considerando las siguientes estrategias:\nOfrecer un set de letreros a cada estudiante con palabras que contienen los grafemas M y P para que reconozcan su ubicación.\nMostrar ilustraciones de diversos objetos que comienzan con los grafemas M y P para que sus estudiantes los identifiquen.\n¿A qué modelo del aprendizaje de la lectura responden las estrategias utilizadas por el profesor?\nA) Modelo holístico.\nB) Modelo integrado.\nC) Modelo de destrezas.\nD) Modelo transaccional.', 'C', 'Migration_2025_05_27'),
('34 ¿Qué tipo de alteración presenta un estudiante con las siguientes características?\n-Tono laríngeo alterado.\n-Falta de aire para finalizar las frases.\n-Resonancia nasal.\nA) De la voz.\nB) Del tono.\nC) De la nasalidad.\nD) De la respiración.', 'A', 'Migration_2025_05_27'),
('35 ¿Cuál de las siguientes características define a una disartria?\nA) Alteración de la voz producida por un trastorno funcional u orgánico de la laringe.\nB) Articulación defectuosa de las palabras sin una causa sensorial ni motriz atribuible.\nC) Habla lenta y perturbada producto de una lesión del sistema nervioso central o periférico.\nD) Emisiones alteradas de fonemas debido a problemas en los órganos articulatorios periféricos.', 'C', 'Migration_2025_05_27'),
('36 Lea la siguiente situación:\nMargarita es una estudiante de 1° Básico que tiene una condició e paladar ojival. Ella presenta dificultades en la articula ión de los fonemas vocálicos /.y /.y de los fonemas consonánticos /. /.y /.\n¿Qué trastorno del habla es posible que presente Margarita?\nA) Dislalia.\nB) Disfasia.\nC) Disglosia.\nD) Disartria.', 'C', 'Migration_2025_05_27'),
('39 Lea la siguiente situación:\nLos niños y niñas con TEL, por lo general, presentan dificultades en distintas áreas de lenguaje que van desde leves a severas y, en algunos casos, las dificultades son severas en la comprensión y producción morfológica. En este caso, los problemas se relacionan con morfemas gramaticales e inflexiones verbales.\n¿Qué expresión ejemplifica de mejor forma el trastorno descrito?\nA) Cuando se hizo la noche... me gusta la noche.\nB) Cuando se hacieron la noche se sintió mucho fría.\nC) Cando se hicieron la noche se sintió mucho flío.\nD) Cuando se hició la noche se sintió mucho frío.', 'B', 'Migration_2025_05_27'),
('40 Lea la siguiente situación:\nCamila es una estudiante de 5 años que al comunicarse utiliza recurrentemente expresiones como las siguientes:\n-¡Los niñas están contentas!\n-¡Los niños están jugando en la jardín!\n¿Qué elemento del componente morfosintáctico se encuentra alterado en el discurso de Camila?\nA) Concordancia de género-número.\nB) Cierre gramatical.\nC) Conjugación del verbo.\nD) Organización sintáctica.', 'A', 'Migration_2025_05_27'),
('41 Lea el siguiente diálogo entre una profesora y un estudiante de 1° Básico:\nProfesora:Joaquín, ¿sacaste tu colación?\nJoaquín: ¡Colación mía! Shí claro.\nProfesora: ¡Qué rico!, ¿te gustan esas galletas?\nJoaquín: No claro, toma para tú.\nA partir del diálogo anterior, ¿qué componente del lenguaje se observa principalmente afectado en Joaquín?\nA) Semántico.\nB) Fonológico.\nC) Pragmático.\nD) Morfosintáctico.', 'D', 'Migration_2025_05_27'),
('42 Lea la siguiente situación:\nUn profesor de 1º Básico propone la siguiente actividad: jugar a un dominó de figuras geométricas. Para ello, le entrega a cada estudiante tres fichas y explica el juego. El profesor colocala primera ficha al centro y les pregunta: "¿qué figuras se observan en la ficha?" y "¿quién tiene la ficha que podría continuar el dominó?". El estudiante que la tiene coloca la ficha a continuación de la que está en el centro, y luego continúan el juego, respetando los turnos de cada uno.\n¿Qué componente del lenguaje se pretende promover con la actividad descrita en la situación anterior?\nA) Sintáctico.\nB) Semántico.\nC) Morfológico.\nD) Pragmático.', 'D', 'Migration_2025_05_27'),
('43 Lea la siguiente situación:\nUna profesora de 1º Básico expone a su curso una ruleta que tiene cuatro imágenes: una niña, un niño, un sol y la lluvia. Luego le entrega un set de 6 tarjetas a cada uno con prendas de vestir.\nProfesora:Gastón, pasa adelante a mover la ruleta.\nGastón:Me salió el sol.\nProfesora: ¡Muy bien!, preguntemos a tus compañeros: ¿qué ropa uso cuando h ce mucho calor?\nFlorencia: Uso falda, yo uso falda.\nProfesora:Muy bien, Florencia, ahora pasa tú adelante a mover la ruleta.\n¿Qué componente del lenguaje es posible favorecer con la experiencia didáctica descrita en la situación anterior?\nA) Semántico.\nB) Fonológico.\nC) Pragmático.\nD) Morfosintáctico.', 'A', 'Migration_2025_05_27'),
('44 ¿Cuál de las siguientes actividades es la más pertinente para promover la estructuración oral de enunciados de un estudiante?\nA) Numera las imágenes para formar la oración: La niña come manzana.\nB) Coloca el número que corresponda para ordenar la secuencia.\nC) Arma y repite la siguiente oración: Un niño sopla las velas de la torta de cumpleaños de su hermana.\nD) Descubre los tres absurdos y coméntalos.', 'C', 'Migration_2025_05_27'),
('45 Lea la siguiente situación:\nUna profesora de 1° Básico está trabajando con sus estudiantes l s palabras inversas o bifrontes. Para ello, reparte lassiguientes imágenes a cuatro niños del curso:\nProfesora:Niños, miren su imagen y la de sus compañeros.\nNiños: Yaaaa...\nProfesora:Ahora ubíquese cada uno en una esquina distinta de la sala y, cu ndo contemos hasta tres, deben buscar al compañero que tiene la palabra inversa a la de ustedes.\n¿Cuál de las siguientes habilidades fonológicas se encuentra trabajando la profesora con los estudiantes en la situación anterior?\nA) Análisis fonémico.\nB) Síntesis fonémica.\nC) Identificación silábica.\nD) Reconocimiento de rimas.', 'A', 'Migration_2025_05_27'),
('46 Lea la siguiente situación:\nUn profesor de 1° Básico le presenta a Martín, un niño de 6 años que tiene dificultades pragmáticas, una secuencia de actividades. Lea el diálogo que mantienen en el transcurso de las actividades:\nProfesor: (Sobre la mesa hay 5 sombreros distintos). Martín, por favor entrégame el sombrero.\n(Martín le entrega un sombrero).\nProfesor: ¿Cómo supiste cuál sombrero quería yo?\nMartín: (Levanta los hombros). No sé.\nProfesor: (Sobre la mesa hay 5 lápices de distinto color). Martín, por favor, entrégame el lápiz.\nMartín: ¿Cuál?\n¿Cuál de las siguientes habilidades pragmáticas está trabajando el profesor con Martín en la situación anterior?\nA) Manejo del tópico.\nB) Fórmulas de cortesía.\nC) Solicitudes de aclaración.\nD) Descripciones declarativas.', 'C', 'Migration_2025_05_27'),
('47 Lea la siguiente situación:\nUna profesora invita a sus estudiantes a jugar a la "silla musical". Les explica que cada vez que suene una canción deben caminar alrededor de las sillas, pueden bailar incluso, percuando la música se detiene deben ubicarse en el primer asiento que encuentren. El estudiante que se queda sin silla debe salir del juego. Esto se realiza sucesivamente hasta que queda un único niño.\n¿Cuál de las siguientes habilidades fonológicas se encuentra ejercitando la profesora?\nA) Atención auditiva general.\nB) Discriminación auditiva selectiva.\nC) Distinción de secuencias de sonidos.\nD) Reconocimiento de fuente sonora.', 'A', 'Migration_2025_05_27'),
('48 Una docente de 3° Básico presenta a sus estudiantes la oración "Se rompió la ........ de este libro", y les muestra las siguientes imágenes:\n[Imagen de una hoja, Imagen de un lomo de libro]\nLuego les pide que determinen cuál de las dos imágenes completa correctamente la frase. ¿Cuál de las siguientes relaciones semánticas se encuentra estimulando la profesora con la actividad descrita?\nA) Polisemia.\nB) Hiperonimia.\nC) Sinonimia.\nD) Homonimia.', 'A', 'Migration_2025_05_27'),
('49 Observe las siguientes imágenes:\n[Secuencia de 3 imágenes: Niño corriendo, Niño cayendo, Niño con curita en la cabeza]\nLa profesora les presenta la primera y última lámina a los estudiantes, omitiendo la central, y realiza las siguientes preguntas:\nProfesora: ¿Qué hace el niño? (Muestra la lámina 1).\nEstudiante: Está corriendo.\nProfesora: ¿Qué le pasó aquí? (Señala la lámina 3).\nEstudiante: ¡Se pegó en la cabeza!\nProfesora: ¿Qué le habrá sucedido?\nEstudiante: Yo creo que se pegó con algo... es que estaba corriendo fuerte.\nProfesora: ¿A alguno de ustedes le ha pasado algo similar?\nEstudiante: Sí... Yo una vez me caí en la plaza, porque estaba corriendo y me dolió.\n¿Cuál es la habilidad del componente semántico que más se favorece con la actividad presentada?\nA) Asociación.\nB) Clasificación.\nC) Inferencia.\nD) Evaluación.', 'C', 'Migration_2025_05_27'),
('50 Lea la siguiente situación:\nUna profesora realiza la siguiente actividad para trabajar la conciencia fonológica:\nProfesora: Yo les voy a decir una palabra y ustedes deben buscar palabras que comiencen con el sonido final de la palabra dada. La palabra es mesassssss.\nValentina: Sapo.\nProfesora: Muy bien, mesasss termina con el sonido o fonema /.y ssssapo comienza con /. Tomás, dime, por favor, una palabra que comience con el sonido o fonema final de sapooo.\nTomas: Ola.\nProfesora: Muy bien, ¿con qué sonido termina sapooo?\nTomás: Con /beberofesora: ¿Y con qué sonido comienza ola?\nValentina: Con /beberofesora: Si nuestra palabra ahora es olaaaaa, ¿podemos usar la palabra indio?\nValentina: No, porque indio no empieza con /beben¿Cuál es la habilidad de la conciencia fonológica que más se favorece con la actividad presentada?\nA) Identificación silábica.\nB) Discriminación de pares mínimos.\nC) Análisis fónico.\nD) Memoria auditiva.', 'C', 'Migration_2025_05_27');
