-- Migration part 3
INSERT INTO study_app.preguntas (text_content, respuesta_correcta, raw_source) 
VALUES 
('51 Lea el siguiente diálogo:\nProfesora: Vamos a formar la oración "Luis bebe agua". Ahora vamos a segmentar la oración /bebebe/-/agua/. ¿Cuántas palabras tiene la oración?\nValentina: Tres.\nProfesora: Muy bien, yo dije "Luis bebe agua". Esta oración tiene tres palabras, ¿cuáles son esas palabras?\nVíctor: Luis.\nProfesora: Muy bien, esa es una, ¿cuál otra?\nValentina: Bebe.\nProfesora: ¿Y cuál es la última?\nVíctor: Agua.\nProfesora: Bien, ¿cuántas palabras tiene la oración "Luis bebe agua helada"?\nNicolás: Cuatro.\nProfesora: Muy bien; ¿cuál es la diferencia entre Luis bebe agua y Luis bebe agua helada?\n¿Cuál es la habilidad del componente morfosintáctico que se favorece con la actividad presentada?\nA) Conciencia sintáctica.\nB) Concordancia nominal.\nC) Concordancia de preposiciones.\nD) Cierre gramatical.', 'A', 'Migration_2025_05_27'),
('52 Lea la siguiente situación:\nUn profesor quiere que los estudiantes trabajen el componente pragmático a partir de la siguiente actividad:\nSu nombre es "Adivina quién soy". Se divide el curso en dos grupos. Uno de ellos escoge un personaje oculto, cuidando de que no sea descubierto, mientras que el otro grupo tendrá que adivinar a qué personaje se hace referencia.\n¿Cuál de las siguientes estrategias sería pertinente para el logro del objetivo que se propone el profesor?\nA) Pedir la clasificación gramatical de las palabras que aparecen en los enunciados de los estudiantes.\nB) Solicitar la construcción de oraciones completas al responder a las preguntas.\nC) Intencionar la toma de turnos en las preguntas y respuestas que se realizan en el juego.\nD) Trabajar el descubrimiento del significado de las palabras desconocidas que surgen en el juego.', 'C', 'Migration_2025_05_27'),
('53 Lea la siguiente situación:\nCarolina: Mira el conejo.\nVicente: ¿Cuál?\nCarolina: El que te hace leso.\nVicente: ¿Dónde?\nCarolina: Era broma, poh.\nVicente: ¡Ah!\n¿Cuál de las siguientes actividades permite desarrollar la habilidad que se observa disminuida en Vicente?\nA) Actividades de identificación de absurdos visuales.\nB) Actividades que favorezcan la adquisición de léxico.\nC) Actividades de reconocimiento de intenciones de las personas.\nD) Actividades de reconocimiento de expresiones faciales y gestos.', 'C', 'Migration_2025_05_27'),
('54 Lea la siguiente situación:\nJorge, de 6 años, presenta TEL. Mientras participaba en el juego de ponerle la cola al burro con sus compañeros, se le escuchaba dar instrucciones: "Alelante... ahora atás". La profesoraobservó errores en la producción de palabras de Jorge.\n¿Cuál de las siguientes acciones resultaría más pertinente que el estudiante realizara para abordar su desafío?\nA) Tareas de estructuración de instrucciones.\nB) Ejercicios de praxias articulatorias.\nC) Actividades de contraste de fonemas.\nD) Relaciones léxicas de conceptos de ubicación espacial.', 'C', 'Migration_2025_05_27'),
('55 Lea el siguiente ejemplo:\nProfesora: ¡Qué lindos tus zapatos nuevos!\nCristóbal: Mi zapatos.\nProfesora:Sí, son tuyos los zapatos.\nCristóbal: Son rápido.\nProfesora:Son unos zapatos muy rápidos.\n¿Qué estrategia de facilitación utiliza la profesora para favorecer el desarrollo morfosintáctico de Cristóbal?\nA) Contracción.\nB) Inducción.\nC) Expansión.\nD) Énfasis prosódico.', 'C', 'Migration_2025_05_27'),
('56 Lea la siguiente situación:\nUn curso de 1º Básico se encuentra terminando una actividad cuando suena el timbre.\nProfesor: Niños, pueden salir a recreo.\nSofía:Tío, voy saliendo para adentro.\nProfesor: ¿Vas a hacer qué?\nSofía:Voy saliendo al patio.\n¿Cuál de los siguientes procedimientos utiliza el profesor para corregir a Sofía?\nA) Pedir a la niña que repita su enunciado.\nB) Pedir a la niña que clarifique su enunciado.\nC) Enfatizar lo que dijo la niña, pero correctamente.\nD) Solicitar a la niña que estructure correctamente la oración.', 'B', 'Migration_2025_05_27'),
('57 Lea el siguiente diálogo entre una profesora y sus estudiantes:\nProfesora:¿Quién sabe lo que es esto?\nJulio: Una pelota.\nProfesora: ¡Muy bien! ¿Qué tipo de pelota es?\nManuel: Una pelota de fúbol...\nProfesora:¿Y cómo sabes que es de fútbol?\nManuel: Mi papá tiene una que se parece harto.\nProfesora:¿Qué características tienen las pelotas de fútbol?\nJulio: Son blancas con negro...\n¿Por qué la práctica pedagógica anterior es apropiada para promover el desarrollo del lenguaje?\nA) Modifica las características de la espontaneidad en función del hilo conductor del diálogo.\nB) Fomenta la actividad conjunta, incorporando contenidos funcionales al lenguaje del niño.\nC) Mantiene un habla formal inteligible que permite a los niños/as integrarse a la conversación.\nD) Provee un contexto socialmente significativo para la interacción académica formal docente-niño.', 'B', 'Migration_2025_05_27'),
('58 ¿Cuál de los siguientes recursos materiales permite trabajar el componente semántico en estudiantes que presentan TEL?\nA) Tablero que facilite la comunicación.\nB) Fichas que trabajen categorías léxicas.\nC) Tarjetas que trabajen la memoria visual.\nD) Juego que incentive la segmentación silábica.', 'B', 'Migration_2025_05_27');
