-- Migration to add the rest of the questions
INSERT INTO study_app.preguntas (text_content, respuesta_correcta, raw_source) 
VALUES 
('11 Lea y observe el siguiente registro de TEPROSIF-R:\nNombre: Javiera.\nEdad: 5 años.\nÍtems Registro Estructura silábica Asimilación Sustitución\nAuto Amto 1\nIndio Injo 1 1\nMicro Miko 1\nHelicóptero Helikortero 1\nCuaderno Kudemno 1\nPlátano Patano 1\nPlancha Pancha 1\nPantalón Patalo 2\nÁrbol Abol 1\nGuante Gate 1\nCaperucita Capelucita 1\nSegún los resultados del registro de TEPROSIF-R, ¿qué dificultad fonológica se observa con mayor frecuencia en las emisiones de Javiera?\nA) Asimilación vocálica.\nB) Aspiración de fonema trabante.\nC) Reducción de grupos consonánticos.\nD) Sustitución de fonemas líquidos entre sí.', 'C', 'Migration_2025_05_27'),
('13 Lea la siguiente situación:\nEn una clase de ciencias, un estudiante logra comprender el concepto de cambios de la materia a partir de una actividad en la que experimentó con los distintos estados del agua. No obstante, al pedirle que entregue una definición sobre este concepto, no lo logra.\nSegún la Teoría Evolutiva Psicogenética del Desarrollo de Jean Piaget, ¿en qué etapa del desarrollo se encuentra este estudiante?\nA) Etapa sensoriomotriz.\nB) Etapa preoperacional.\nC) Etapa de operaciones concretas.\nD) Etapa de operaciones formales.', 'C', 'Migration_2025_05_27'),
('14 ¿Cuál de las siguientes opciones presenta una característica de la función cognitiva "atención"?\nA) Involucra el tiempo de duración de un estímulo.\nB) Se encarga de la recepción de un solo estímulo.\nC) Actúa como filtro de los estímulos más relevantes.\nD) Permite la organización de la información sensorial.', 'C', 'Migration_2025_05_27'),
('15 Lea la siguiente situación:\nCamila sufrió un accidente automovilístico. Junto a ella iba su bebé de 8 meses, quien sufrió una lesión en el hemisferio izquierdo del cerebro. Después de la etapa de holofrases, el niño comenzó a presentar problemas en su lenguaje. No obstante, el hemisferio derecho compensó la mayoría de las funciones lingüísticas comprometidas, permitiéndole producir palabras, comprender su significado, realizar asociaciones entre ellas, establecer contacto visual y hacer peticiones. Sin embargo, continuócon dificultad en la construcción de oraciones.\n¿Qué área del lenguaje del niño se vio afectada por la lesión en el hemisferio izquierdo de su cerebro antes del año?\nA) Fonológica.\nB) Semántica.\nC) Pragmática.\nD) Morfosintáctica.', 'D', 'Migration_2025_05_27'),
('16 ¿Cuál de las siguientes actividades que favorecen el desarrollo de las habilidades psicolingüísticas contribuye principalmente a la comprensión auditiva?\nA) Reproducción de trabalenguas.\nB) Seguimiento de instrucciones en un juego.\nC) Nominación de objetos propios de una categoría.\nD) Completación de palabras a partir de la primera sílaba.', 'B', 'Migration_2025_05_27'),
('17 ¿Cuál de los siguientes enunciados presenta uno de los principales planteamientos teóricos de Lev Vygotsky?\nA) El lenguaje es un resultado del desarrollo cognitivo derivado de la inteligencia.\nB) El lenguaje obedece a un procesamiento lingüístico propio, del cual surgen reglas gramaticales universales.\nC) El lenguaje se adquiere a partir de la interacción con los diversos estímulos externos existentes.\nD) El lenguaje es el principal vehículo de interacción social que influye en el desarrollo del pensamiento.', 'D', 'Migration_2025_05_27'),
('18 Lea la siguiente situación:\nUna niña de cinco años se encuentra jugando con un adulto cuidador que le propone la siguiente actividad: "Arma este puzle, pero recuerda que debes observar muy bien las imágenes y juntar solo aquellas que se parecen en formas y colores, tal como en esta foto". La niña observa la imagen principal y comienzaa seleccionar las piezas, mientras comenta para sí misma: "¡Ah!, esta es la cabeza del dinosaurio, va con esta". Luego toma otra pieza. "¡Ah, no! este es el río, no va con el dinosaurio".\nAplicando los postulados de Luria, ¿qué función cumple el lenguaje de la niña en la situación anterior?\nA) Incita la actividad y desinhibe el comportamiento durante el juego.\nB) Genera un estímulo independiente del contenido de las emisiones.\nC) Permite que la acción predomine sobre el lenguaje propio o interno.\nD) Permite la autorregulación de la conducta para concretar la actividad.', 'D', 'Migration_2025_05_27'),
('19 Lea la siguiente situación:\nComo parte de la clase de Ciencias Naturales los estudiantesde 1° Básico realizan una disertación sobre sus animales favoritos. En una de las presentaciones, Juan quiere saber más sobre el animal que expone su compañero y le hace preguntas.\nSegún lo definido por Halliday, ¿qué función del lenguaje predomina en la intervención de Juan?\nA) Función heurística.\nB) Función reguladora.\nC) Función personal.\nD) Función interaccional.', 'A', 'Migration_2025_05_27'),
('20 Lea la siguiente situación:\nCarlos, de siete meses, se encuentra junto a su cuidadora cuando comienza a gritar insistentemente. Ella lo mira y le pregunta "¿Qué pasa, Carlitos?". El bebé continua balbuceando "ahh""eehhh" con gran persistencia, mientras abre y cierra su mano observando fijamente un juguete. Ella toma un osito de génerode muchos colores, se lo entrega al bebé y le dice: "Ahhh... ¡qué lindo!, este le gusta a mi bebé...".\n¿Cuál de las funciones del lenguaje propuestas por Halliday queda manifiesta en la conducta del bebé?\nA) Imaginativa.\nB) Heurística.\nC) Instrumental.\nD) Interaccional.', 'C', 'Migration_2025_05_27'),
('21 Según lo que plantea Jacobson, ¿en qué se centra el mensaje en la función referencial del lenguaje?\nA) Emisor.\nB) Código.\nC) Mensaje.\nD) Contexto.', 'C', 'Migration_2025_05_27'),
('23 Lea el siguiente párrafo:\nGracias al dominio de la lingüística generativa durante losaños sesenta, se comprendió esta dimensión del lenguaje como la encargada de explicar los fenómenos organizativos y estructurales de las lenguas. Algunas de las unidades que corresponden a su estudio son el enunciado, la oración y frase (Acosta y Moreno, 1999).\n¿Qué componente del lenguaje se define en el párrafo anterior?\nA) Sintáctico.\nB) Semántico.\nC) Pragmático.\nD) Morfológico.', 'A', 'Migration_2025_05_27'),
('24 Lea el siguiente diálogo entre una educadora y una estudiante:\nEducadora: María, ¿qué hiciste el fin de semana?\nMaría: Jubé pon el bato.\nEducadora: Ahhh, y ¿cómo se llama tu gato?\nMaría: Batito, poh.\n¿Cuál es el punto articulatorio de los fonemas sustituidos por María?\nA) Velar.\nB) Dental.\nC) Palatal.\nD) Bilabial.', 'A', 'Migration_2025_05_27'),
('25 Lea la siguiente situación:\nUna profesora especialista del PIE y la profesora jefe del 1°Básico se encuentran planificando la clase de Lenguaje y Comunicación, en la que los estudiantes escribirán una cartde agradecimiento a Carabineros de la comuna por haberlos rcibido el pasado día 27 de abril. Ambas docentes proponen las siguientes actividades para redactar la carta:\nRealizar una lluvia de ideas de todo lo que quieren decir los niños en la carta.\nDefinir los componentes de la carta, realizando preguntas: ¿para quién es la carta?, ¿qué queremos decir?, ¿quiénes se despiden?, etcétera.\nResponder a la pregunta: ¿qué fue lo que nos ayudó a escribir la ca ta?\n¿A cuál de las siguientes estrategias, para trabajar el proceso de escritura, recurrieron las docentes en su planificación?\nA) Escritura espontánea.\nB) Escritura guiada.\nC) Escritura creativa.\nD) Escritura consensuada.', 'B', 'Migration_2025_05_27'),
('26 Lea la siguiente situación:\nEn la clase de Lenguaje y Comunicación, en un 4° Básico, un profesor propone el objetivo de aprendizaje "Escribir artículos informativos para comunicar información sobre un tema". Para ello, los estudiantes escogen un tema de su interés y buscan, leen y registran información sobre este. El profesor le entrega acad estudiante un organizador gráfico para que sinteticen en él las ideas principales de los textos revisados.\n¿En qué fase de la escritura se enmarca la estrategia descrita en la situación anterior?\nA) Edición.\nB) Revisión.\nC) Planificación.\nD) Textualización.', 'C', 'Migration_2025_05_27'),
('27 En relación con las etapas de la producción de textos escritos, ¿cuál de las siguientes opciones presenta uno de los propósitos de la fase de textualización?\nA) Organizar la estructura y contenido del texto.\nB) Realizar evaluaciones respecto del contenido del texto.\nC) Reparar en las normas de organización textual y de orden textual.\nD) Activar mentalmente la información sobre aspectos retóricos y de contenido.', 'C', 'Migration_2025_05_27'),
('28 Lea la siguiente situación:\nTras la lectura de la fábula "El flautista de Hamelín", la profesora les pregunta a los estudiantes: "¿Les parece correctolo que hizo el flautista al final del cuento? ¿Qué habrían hecho ustede n su lugar?".\n¿Qué tipo de pregunta realizó la profesora a sus estudiantes?\nA) Crítica.\nB) Creativa.\nC) Explícita.\nD) Implícita.', 'A', 'Migration_2025_05_27'),
('29 ¿Cuál de las siguientes actividades es pertinente para trabajar en el momento "después de la lectura"?\nA) Realizar mapas conceptuales.\nB) Interrogar ilustraciones del texto.\nC) Responder preguntas que guían la lectura.\nD) Realizar hipótesis en la lectura del texto.', 'A', 'Migration_2025_05_27'),
('30 ¿Cuál de las siguientes actividades trabaja la adquisición de la lectura desde un modelo holístico?\nA) Realizar juegos de palabras identificando su sonido inicial.\nB) Ordenar palabras alfabéticamente a partir de material de su entorno.\nC) Realizar la actividad "jugar a leer" con cuentos conocidos por los estudiantes.\nD) Reconocer número de sílabas de palabras significativas para los estudiantes.', 'C', 'Migration_2025_05_27');
